### ISSUE TITLE
Reunião - Primeiro contato (IEPHA) - 01.08.2024

### ISSUE THREAD

**Issue by raianecardoso** [automatiza-mg/nucleo-imersoes#14]
# Reunião - Primeiro contato (IEPHA) - 

Data: 01.08.2024
Horário: 10h 
Participantes: 
Raiane Souza
Yan Carmo 
Henrique Romano 
Cleison Carvalho (Gerência de Logística Manutenção e Modernização Institucional/GLMMI - DPGF)
Roberto Prates (Coordenador do Núcleo de Contabilidade e Finanças I NCF - DPGF)
Edwilson Martins (DPGF)

## Demanda
**Pedido**: 
- Lançamento de notas Fiscais, conformidades, empenho, liquidação e pagamento.

**Descrição**: 
- O processo consiste em efetuar o lançamento das notas fiscais no portal de compras, efetuar conformidades, entrar no siafi e e realizar empenhos, liquidação e pagamentos.

**Métricas**
- Selecione uma opção para indicar a frequência com que seu processo acontece: Diário
- Insira o número de vezes que o processo acontece dentro do período selecionado acima: 10
- Preencha, ainda que de maneira estimada, os minutos gastos para realizar uma rodada completa do processo: 60

## Discussão

- As atividades no Portal de Compras é o grande volume de trabalho do setor. No entanto, há uma demanda urgente de execução de despesas de editais do FEC. Seriam cerca de 220, podendo chegar até 300, processo de empenho, liquidação e pagamentos entre outubro, novembro e dezembro (até o fim do ano fiscal).
- Os editais ainda serão publicados - estão no jurídico.
- Secult já executa esse processo, aparentemente, já automatizado.
-  A equipe do IEPHA ainda não tem o processo estruturado. Será realizada uma reunião com a Secult para que eles possam reproduzir o processo da Secult.

## Encaminhamentos

- Ficou acordado que a equipe do Automatiza irá participar da reunião com a Secult para entender o processo. Após essa reunião, será definido se o pedido do IEPHA será atendido ou não.

**Comment by raianecardoso** [comment]
Reunião IEPHA e Secult - 08.08.2024

Regina DCF/Secult
Murillo 


- Tem robô para a liquidação e pagamento. Não tem robô para liquidação. 
- Na secult, a TI desenvolveu o robô e as planilhas base. Para o processo de empenho, um servidor treinado, empenha mais rápido que o robô + alimentação da planilha

**Comment by YanVieira1905** [comment]
> Reunião IEPHA e Secult - 08.08.2024
> 
> Regina DCF/Secult Murillo
> 
> * Tem robô para a liquidação e pagamento. Não tem robô para liquidação.
> * Na secult, a TI desenvolveu o robô e as planilhas base. Para o processo de empenho, um servidor treinado, empenha mais rápido que o robô + alimentação da planilha

@raianecardoso, eles chegaram a mostrar o robô? Ele é feito no Power Automate Desktop mesmo? Confesso que achei estranho o robô ser mais lento do que o servidor. 

Fiquei na dúvida pelo post se tem ou não robô de liquidação. 

Sobre a facilidade de adaptação, qual a opinião de vocês? Conseguem estimar um prazo para o projeto?

**Comment by raianecardoso** [comment]
> > Reunião IEPHA e Secult - 08.08.2024
> > Regina DCF/Secult Murillo
> > 
> > * Tem robô para a liquidação e pagamento. Não tem robô para liquidação.
> > * Na secult, a TI desenvolveu o robô e as planilhas base. Para o processo de empenho, um servidor treinado, empenha mais rápido que o robô + alimentação da planilha
> 
> @raianecardoso, eles chegaram a mostrar o robô? Ele é feito no Power Automate Desktop mesmo? Confesso que achei estranho o robô ser mais lento do que o servidor.
> 
> Fiquei na dúvida pelo post se tem ou não robô de liquidação.
> 
> Sobre a facilidade de adaptação, qual a opinião de vocês? Conseguem estimar um prazo para o projeto?

Yan, quando você viu o comentário, eu estava editando no meio da reunião, que terminou agora, por isso não estava fazendo muito sentido 😅 ! Já atualizei relato no comentário acima. 


Respondendo suas outras questões:

- Eles não mostraram o robô. O robô está em posse da Ti, que não participou da reunião.
- Isso, Power automate desktop.
- No caso, faz sentido demorar mais porque foi feito um esforço inicial de montar a base de dados utilizada pelo robô. No processo manual, o servidor extrai as informações do sei e executa diretamente no siafi. No processo com o robô, a etapa de transcrição das informações, que provavelmente é a mais demorada, foi mantida, mas agora  para um arquivo CSV. O robô, executa a partir desse arquivo. 
- Existem o robô para liquidação, porém não foi usado.
- Sobre a facilidade de adaptação, passo minhas impressões na reunião de equipe.
