### ISSUE TITLE
Reunião de Primeiro Contato - InvestMinas - 22/08/2024

### ISSUE THREAD

**Issue by raianecardoso** [automatiza-mg/nucleo-imersoes#17]
# Reunião - Primeiro contato (InvestMinas) - Minas Maps.
Data: 22.08.2024
Horário: 11h
Participantes:
@raianecardoso 
@Andrelamor 
Davyson Demmer Guimaraes Barbosa: <davyson.demmer@investminas.mg.gov.br>

## Demanda

**Pedido**:
Atendimento do Minas Maps.

**Descrição**:
Atualmente utilizamos o sistema ArcGis On Line para armazenar informações de imóveis disponíveis em Minas Gerais para receber investimentos. Estamos fazendo uma atualização do sistema com a ajuda da equipe do LAB.mg em que foi detectada a necessidade de usuários de saberem mais informações sobre o que é o sistema e quais são as soluções que o sistema se propõe a apresentar soluções. Portanto, acreditamos que a opção de incluir um chatbot numa aba "Fale Conosco" poderia ser interessante para auxiliar no esclarecimento de dúvidas dos usuários da plataforma de informações georreferenciadas.

**Links:**
- [site - nova versão](https://experience.arcgis.com/experience/e7a6231fde8b4cde9175ebe1839cbdd5/page/Mapa-Simples/)
- [chatbot via integração com a power platform da MIcrosoft:](https://experience.arcgis.com/experience/e7a6231fde8b4cde9175ebe1839cbdd5/page/Fale-Conosco/)
- [relatório para os imóveis cadastrados no sistema](https://drive.google.com/file/d/1U2AHaonaYwTfVAyvzACYn_NdjXNfyzOc/view?usp=sharing)

**Métricas:**
Selecione uma opção para indicar a frequência com que seu processo acontece: Diário
Insira o número de vezes que o processo acontece dentro do período selecionado acima: 1
Preencha, ainda que de maneira estimada, os minutos gastos para realizar uma rodada completa do processo: 05

## Discussão
- Em reunião,  o demandante apresentou **duas demandas de automação**. 
     1. Um chatbot para responder perguntas no site; e
     2. A produção de um relatório de terrenos disponíveis para investimentos. 
- O demandante informou que está realizando o curso de Power Automate. 

_**1. Demanda Chatbot**_
- O demandante quer sugestões de ferramenta de chatbot. O que foi criado (link acima) terá duração de apenas 60 dias, considerando a limitações do pacote do MS 365 contratado.
- A TI do órgão contratou o Chat GPT 4, então o demandante está considerando desenvolver o novo chatbot utilizando esta contratação.

_**2. Demanda Relatório:**_ 
- A INVESTMINAS disponibiliza em seu site um relatório (pdf) e uma planilha com as informações dos terrenos disponíveis para investimento
- Este relatório é gerado em duas etapas:
    1.  a primeira, no Qgis, onde são geradas imagens (mapas) e informações resultantes de cálculos; As imagens são salvas em documentos PDF. As informações são coletadas para compor a segunda parte do relatório.
   2. a segunda, consiste no preenchimento de uma planilha, com as informações extraídas do QGIS. Usando o  google apps scripts, é gerado um arquivo PDF de relatório, em modelo pré definido, que fica salvo no Sharepoit. 
- Descrição do Fluxo: 
    1. Entra no Qgis;
    2. Gera informações (cálculo) relativos aos terrenos desejado e de camadas pré definidas (aeroportos, rodovias, subestação de energia, instituição de ensino superior),  bem como os arquivos pdf com as imagens;
    4. Faz upload dos pdfs gerados no QGis para pasta do Sharepoint;
    5. Coleta informações do imóvel desejado calculadas pelo QGis e insere em planilha;
    6. Gera arquivo PDF em modelo de relatório pré definido, que é automaticamente salvo no Sharepoit;
    7. Junta pdfs em um arquivo único, chamado relatório.
    8. Sobe para o site o relatório e a planilha no ArcGis On Line . 

- Atualmente, o site conta com 1.400 imóveis já cadastrados. Destes, 1000 já possuem relatórios, sendo o passivo de 400 relatórios a serem gerados. Ademais, com o cadastro de novo imóveis, tem-se a demanda de novos relatórios. 
-  Na sua rotina, o demandante produz, em média, 80 relatórios em 10 horas de trabalho, trimestralmente

## Encaminhamentos

- Considerando que o demandante está realizando o curso e já tem familiaridade com ferramentas de automação (PowerApps), recomenda-se atendimento na modalidade de curso e mentoria. 
- Dar retorno ao demandante após a reunião de equipe para definição de novos projetos na próximas quarta-feira (28)

**Comment by Andrelamor** [comment]
## 1ª reunião de trabalho
