### ISSUE TITLE
Reunião - Primeiro contato (GMG) - Saldo de Contratos 03/09/2024

### ISSUE THREAD

**Issue by raianecardoso** [automatiza-mg/nucleo-imersoes#26]
# Reunião - Primeiro contato (GMG) - Saldo de Contratos 
Data: 03.09.2024
Horário: 10h
Participantes:
@raianecardoso
@halvesromano 
davidson.oliveira@gabinetemilitar.mg.gov.br
Major Romier (Superintendente SPGF)
Tenente Ewerton ( Diretor de compras e contratos)
Sgt Nogueira (Aest) 
Eliana (Diretoria de Planejamento e Orçamento)

## Demanda
**Pedido:**
Saldo de Contratos.

**Descrição:**
Os contratos geridos pela Diretoria de Suprimentos e serviços, constantemente são atualizados os saldos pelo Portal de Compras e SIAD, entretanto possuímos planilhas que precisamos atualizar frequentemente, pois os sistemas não são conectados. Com a automatização desses processos, conseguiria realizar as atualizações no sistema, sendo automatizado na planilha, automatizando uma Power BI com a visualização dos resultados em informações. São gêneros alimentícios, utensílios utilizados para o governo, que são constantemente perguntados qual o gasto pelo Governo. 

**Métricas:**
Selecione uma opção para indicar a frequência com que seu processo acontece: Diário
Insira o número de vezes que o processo acontece dentro do período selecionado acima: 02
Preencha, ainda que de maneira estimada, os minutos gastos para realizar uma rodada completa do processo: 40

## Discussão
- As consulta são feitas no SIAFI, mas podem ser feitas pelo BO. Hoje, não utilizam o BO por falta de conhecimento de como utilizá-lo, mas têm o acesso para retirar o relatório.
- São extraídas as informações de cada elemento item, se foi empenhado e realizado por exemplo. Eles acompanham as informações daquilo que a execução é rotineira, chamado de "Divisão por 366" na metodologia interna. Os demais, são "sob demanda".
- Além da atividade de extrair as informações, a área também tem a demanda de apresentar as informações de forma gerencial. No caso, eles têm pessoas na equipe que trabalham com Power Bi e Power APPs, que poderiam suprir essa necessidade.
- Foi apresentada a planilha atual que é preenchida manualmente. Em análise, a planilha ainda não atende todas as necessidades da área. Por exemplo, ela é um espelho da situação atual, sem permitir que seja visualizado o histórico de evolução de empenho, liquidação e pagamento.
- Foi discutida a possibilidade da área estruturar uma planilha modelo 'base de dados' com todas as informações que são necessárias. A automação irá ser feita nesta planilha. Em seguida, a equipe de dados atuará sob esta planilha para gerar as informações nos formatos desejados.
-  Foi recomendado que a equipe faça o curso de PA.

## Encaminhamentos
- A área irá estruturar um modelo de banco de dados e fará contato quando este estiver pronto para ser automatizado.

**Comment by halvesromano** [comment]
O Maj Davidson me enviou um e-mail em 24/09/2024, com uma planilha modelo para funcionar como banco de dados do processo deles. Ele aguardo um novo contato para uma agendarmos uma nova reunião e alinhamento dos próximos passos.
@raianecardoso como proceder nesse caso??

**Comment by raianecardoso** [comment]
@halvesromano, 

Eu entendo que a gente deve apresentar para eles os nossos formatos de atendimento. Poderíamos marcar uma reuniã ou manter a comunicação por e-mail, fica a seu critério. Eu posso te apoiar nesse processo. 

A depender da modalidade escolhida, damos o encaminhamento. Se não me engano, esse é um projeto que poderia ser atendido via Curso e Mentoria, o que vc acha? Se concordar, talvez eles possam entrar na próxima rodada. 

Queria escutar a opinião do @YanVieira1905  também. Qualquer coisa, levamos para a reunião de equipe.
