### ISSUE TITLE
Reunião erd 09/07/2024

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/nucleo-imersoes#6]
Sobre o cálculo dos indicadores escrevemos em um rascunho:

> comparações tempo_execucao_manual do pedido com os tempo_execucao_manual dos robôs: dará a taxa de substuição (pq o humano vai reduzir o tempo de trabalho cuidando dos robôs)
> 
> comparação tempo_execuacao_manual do pedido com o tempo_total_pos_robo(calculado pelo banco) = (tempo_execucao_robo + tempo_execucao_manuL) dá a comparação de ganho de eficiência do processo.

@raianecardoso ficou de pensar como calcular a complexidade de cada pedido de apoio. A ideia é unificar esta nota com priorização e automatizar a classificação do formato de atendimento.

**Comment by raianecardoso** [comment]
Indicador complexidade

- Só o Power Automate resolve o ou outras ferramenta  serão necessárias?
    -  Em caso de outras ferramentas serem necessárias, a gente já conhece e domina?
- Tempo :  1) alterações no fluxo (nenhuma, menor que 50%, maior 50%); 2) alteração legislativa (decreto ou lei)

**Comment by gabrielbdornas** [comment]
@raianecardoso, costumo fechar Issues de reunião, acho que fica melhor organizado. Vamos abrir fechar este e abrir um com o "call-to-action" de pensar como calcular a complexidade de cada pedido?
